apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: ildeventgen-getting-high-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.9, pipelines.kubeflow.org/pipeline_compilation_time: '2022-03-25T15:14:04.338751',
    pipelines.kubeflow.org/pipeline_spec: '{"description": "Event Simulation and Reconstruction",
      "name": "ILDEventGen_Getting_high"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.9}
spec:
  entrypoint: ildeventgen-getting-high
  templates:
  - name: hdf5-conversion
    container:
      args: ['git clone --branch kf_pipelines https://github.com/FLC-QU-hep/getting_high.git
          && cd getting_high/kf_pipelines                                 && cp /secret/krb-secret-vol/krb5cc_1000
          /tmp/krb5cc_0 && chmod 600 /tmp/krb5cc_0                                 &&
          python create_hdf5EOS.py --ncpu 4 --rootfile "$0" --outputR "$1" --outputP
          "$2" --branch photonSIM --batchsize 10', /tmp/inputs/input-0/data, getting_high_10GeV,
        '1']
      command: [/bin/bash, -c]
      image: engineren/pytorch:latest
      volumeMounts:
      - {mountPath: /eos, name: eos}
      - {mountPath: /secret/krb-secret-vol, name: krb-secret-vol}
    inputs:
      artifacts:
      - {name: simulation-metadata, path: /tmp/inputs/input-0/data}
    outputs:
      artifacts:
      - {name: hdf5-conversion-metadata, path: /mnt/h5_path}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.9
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
    volumes:
    - hostPath: {path: /var/eos}
      name: eos
    - name: krb-secret-vol
      secret: {secretName: krb-secret}
  - name: hdf5-correction
    container:
      args: ['git clone --branch kf_pipelines https://github.com/FLC-QU-hep/getting_high.git
          && cd getting_high/kf_pipelines                                 && cp /secret/krb-secret-vol/krb5cc_1000
          /tmp/krb5cc_0 && chmod 600 /tmp/krb5cc_0                                 &&
          python correctionsEOS.py --input $0 --outputR "$1" --outputP "$2" --batchsize
          10 --minibatch 100', /tmp/inputs/input-0/data, getting_high_10GeV, '1']
      command: [/bin/bash, -c]
      image: engineren/pytorch:latest
      volumeMounts:
      - {mountPath: /eos, name: eos}
      - {mountPath: /secret/krb-secret-vol, name: krb-secret-vol}
    inputs:
      artifacts:
      - {name: hdf5-conversion-metadata, path: /tmp/inputs/input-0/data}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.9
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
    volumes:
    - hostPath: {path: /var/eos}
      name: eos
    - name: krb-secret-vol
      secret: {secretName: krb-secret}
  - name: ildeventgen-getting-high
    dag:
      tasks:
      - name: hdf5-conversion
        template: hdf5-conversion
        dependencies: [simulation]
        arguments:
          artifacts:
          - {name: simulation-metadata, from: '{{tasks.simulation.outputs.artifacts.simulation-metadata}}'}
      - name: hdf5-correction
        template: hdf5-correction
        dependencies: [hdf5-conversion]
        arguments:
          artifacts:
          - {name: hdf5-conversion-metadata, from: '{{tasks.hdf5-conversion.outputs.artifacts.hdf5-conversion-metadata}}'}
      - {name: simulation, template: simulation}
  - name: simulation
    container:
      args: ['cd /home && git clone --branch kf_pipelines https://github.com/FLC-QU-hep/getting_high.git
          &&                                 git clone --branch v02-01-pre02 https://github.com/iLCSoft/ILDConfig.git
          &&                                 cp /secret/krb-secret-vol/krb5cc_1000
          /tmp/krb5cc_0 && ls &&                                 chmod 600 /tmp/krb5cc_0
          &&                                 cd $PWD/ILDConfig/StandardConfig/production
          &&                                 cp /home/getting_high/kf_pipelines/*
          . &&                                 chmod +x ./generateG4EOS.sh && ./generateG4EOS.sh
          "$0" "$1" ', '1', getting_high_10GeV]
      command: [/bin/bash, -c]
      image: ilcsoft/ilcsoft-centos7-gcc8.2:v02-01-pre
      volumeMounts:
      - {mountPath: /eos, name: eos}
      - {mountPath: /secret/krb-secret-vol, name: krb-secret-vol}
    outputs:
      artifacts:
      - {name: simulation-metadata, path: /mnt/root_path}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.9
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
    volumes:
    - hostPath: {path: /var/eos}
      name: eos
    - name: krb-secret-vol
      secret: {secretName: krb-secret}
  arguments:
    parameters: []
  serviceAccountName: pipeline-runner
